# Generated by Django 4.2.18 on 2025-04-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
