# Generated by Django 5.2 on 2025-04-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_file_file_type_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
