# Generated by Django 5.2 on 2025-04-08 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_folder_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file_type',
            new_name='type',
        ),
    ]
